### ISSUE TITLE
File location and comments

### ISSUE THREAD

**Issue by egabrum** [pytest-dev/pytest-variables#21]
Just as constructive feedback, I'll mention the two reasons why this plugin didn't work for me:

- I added `addopts = --variables variables.json` to my pytest.ini, but this always looks for variables.json in the current folder. I wanted to be able to specify what relative folder from rootdir to use to look for variables.json, as I don't always run my tests from the same folder. 

- No comments allowed in the json file. I know, I know, I was hoping the json would be minimized before parsing.

Otherwise, good idea.

**Comment by RonnyPfannschmidt** [comment]
addopts is unrelated to the variables plugin and variables is unable to affect it in any way

json is standardized - if you want comments use one of the more  feature-full formats

**Comment by davehunt** [comment]
Thank you for your feedback @egabrum!

For your first item, we could perhaps attempt to locate the file within the root directory if it's not found in the current directory. If this is an enhancement you'd like to see, please open a new issue describing your preferred behaviour. I'd be happy to review a patch for this.

For your second item, you can also use Human JSON if you want to include comments: https://github.com/pytest-dev/pytest-variables#human-json
