### ISSUE TITLE
Add ini parser for variables argument

### ISSUE THREAD

**Issue by marincandenza** [pytest-dev/pytest-variables#31]
Our Use-Case is to have a platform yaml file and overwrite it with a second user yaml file. 

Would it be possible to add **parser.addini()** for variables? 

Duplicates won't work in pytest ini files which is fine for us.

**Comment by BeyondEvil** [comment]
Hi @marincandenza and sorry for late reply. Holidays and whatnot.

So, let's see if I understand what you're looking for.

You want to be able to set what file (yaml in your case) to read variables from?

Something like:

```ini
[pytest]
variables = /path/to/file.yml
```

**Comment by marincandenza** [comment]
Hi Jim,

Thank your reply.

That's what I'm looking for.

Kind regards
Thomas Wegmann

Jim Brännlund <notifications@github.com> schrieb am Di., 7. Jan. 2020,
12:25:

**Comment by BeyondEvil** [comment]
Awesome @marincandenza 

Could you elaborate a little more on your use case? Specifically regarding "platform" vs. "user". Does platform mean CI? User mean developer running locally? Mind sharing the commands that you're running currently in the different situations, and what you would expect them to look like with the proposed change?

What would you expect to take precedence for overlapping variables, the command line or the pytest.ini reference?

What would you expect to happen with non-overlapping variables, merged or ignored?

Thanks!

**Comment by marincandenza** [comment]
Hi Jim,

we use Jenkins CI and test embedded systems. pytest-variables helps us to
define (currently in YAML)  one environment containing properties to make
the test host ready for testing and to initialize additional hardware and
software, e.g. power supply, servers, etc. We also have a section called
DUT (device under test) that has all properties for "making the DUT ready
for testing". Test case specific data is separated into json files, classes
etc.

Our first YAML file contains the properties for CI and I called it platform
because most of it should also apply to the user (developer, tester, etc.).

If a bug occurs our developers usually have to check-out the repo to start
one or several tests to identify the root cause locally. The "user" has its
own variables / YAML file overwriting some properties of the platform (CI)
variables.

To make the workflow more friendly for user / local execution I would like
to minimize the command line args.

Therefore, my suggestion would be that pytest.ini is read in first, the
command line argument overwrites the variables from pytest.ini and
overlapping variables get merged. It is should be the same behaviour as
giving two command line args (files get merged).

Thank you for pointing this out.

Do you think this workflow could also help other pytest-variables user?

mar.incandenza


Jim Brännlund <notifications@github.com> schrieb am Mi., 8. Jan. 2020,
23:39:

**Comment by RonnyPfannschmidt** [comment]
would simply adding this to the `addopts` option already work?

aka
```ini
[pytest]
addopts= --variables /path/to/file.yml
```

**Comment by marincandenza** [comment]
@RonnyPfannschmidt Thank you for your suggestion. It works fine! 
I added the CI / platform YAML to pytest.ini and the user's YAML in PyCharms Run Configuration -> Additional Arguments. 

This ticket can be closed.

Thank you!

**Comment by RonnyPfannschmidt** [comment]
@marincandenza im glad this helped, happy testing
